// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Summary struct {
	Username  string
	Password  string
	Responded bool
	Gold      sql.NullString
	Silver    sql.NullString
	Bronze    sql.NullString
}
