// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: summary.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT username, password, responded
FROM summary 
WHERE username=$1
`

type GetUserRow struct {
	Username  string
	Password  string
	Responded bool
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.Username, &i.Password, &i.Responded)
	return i, err
}
